name: Release
on:
  push:
    tags: 
      - 'v*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22.4

      - name: Build project
        run: go build .

      - name: Archive production artifacts
        run: tar czvf cs-cli.tar.gz cs-cli

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.x'

      - name: Install dependencies
        run: gem install bundler:2.1.4

      - name: Set up Brew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
          echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> /home/runner/.profile
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

      - name: Publish to Brew
        run: |
          brew bottle --merge --write --no-commit ./Formula/cobra-cli.rb
          git -C $(brew --repo homebrew/core) checkout master
          git -C $(brew --repo homebrew/core) pull
          brew bump-formula-pr --no-browse --no-fork --commit-url=https://github.com/DenisOzindzheDev/cs-cli/releases/tag/v0.0.1 --strict cs-cli